services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=postgres'
      - 'POSTGRES_PASSWORD=djavid'
      - 'POSTGRES_USER=djavid'
    ports:
      - "5432:5432"

  # Сервис Redis
  redis:
    image: redis:7-alpine
    container_name: redis_container
    ports:
      - "6379:6379"
    restart: always
